### ISSUE TITLE
Request support for installation through Scoop

### ISSUE THREAD

**Issue by photkey** [ipinfo/mmdbctl#22]

**Comment by abdullahdevrel** [comment]
The IPinfo CLI (https://github.com/ipinfo/cli) is available via Scoop. The IPinfo CLI actually includes the MMDBctl tool inside it.

If you want to install the MMDBctl tool using Scoop, you can install the IPinfo CLI instead and use it's `mmdb` command.

```
scoop bucket add main
scoop install main/ipinfo-cli
```
