### ISSUE TITLE
File extensions not triggering default flags in import 

### ISSUE THREAD

**Issue by rm-Umar** [ipinfo/mmdbctl#3]
According to `mmdbctl import` help the file extensions should trigger the default flag 
``` bash 
    -t, --tsv
      interpret input file as TSV.
      by default, the .tsv extension will turn this on.
``` 
but it's giving error if we don't specify the flag explicitly 
``` bash 
$ mmdbctl import abc.csv 
err: input file type unknown
```
Giving error on `json` and `csv` as well

**Comment by UmanShahzad** [comment]
This is because the input is not given via arguments, it's given via the `-i` or `--input` flag.
