### ISSUE TITLE
1.4.4 deb.sh script downloads 1.4.3

### ISSUE THREAD

**Issue by derfryday** [ipinfo/mmdbctl#36]
Hello,

the release 1.4.4 `deb.sh` file located at https://github.com/ipinfo/mmdbctl/releases/download/mmdbctl-1.4.4/deb.sh downloads version `1.4.3` rather then `1.4.4`.

**Comment by max-ipinfo** [comment]
@derfryday thank you for the heads-up! 

Looking at the current Github workflow, we do not update the package scripts version when new releases are created, but we should!

I will attempt to fix that in the next release. Sorry for the inconvenience.

**Comment by max-ipinfo** [comment]
@derfryday tooling has been fixed moving forward from `1.4.6`.
