### ISSUE TITLE
It does not reutilize data appropriately

### ISSUE THREAD

**Issue by MarianoFacundoArch** [ipinfo/mmdbctl#42]
The results of exporting a csv, such as locations, and reimporting, is impossible to manage.
Maxmind original MMDBs are more optimized to reutilize already present data, further reducing the size. What would be a good approach to improve this?

**Comment by abdullahdevrel** [comment]
Thank you for your question! I'd appreciate a bit more context to better understand your issue.

> It does not reutilize data appropriately

From what I know, the data in MMDBs is compressed and compiled into a structure optimized for reducing file size. Could you clarify what specific issue you're encountering that makes it seem otherwise?

> MaxMind original MMDBs are more optimized to reutilize already present data

Could you elaborate on why you believe that’s the case? Since mmdbctl is a deterministic system, the process for creating MMDB files should reliably optimize and reuse data where possible. If you're noticing a discrepancy, it might be helpful to dig into how the data is being prepared or structured before using mmdbctl.

Thanks.

Best Regards,
Abdullah (DevRel @ IPinfo.io)

**Comment by MarianoFacundoArch** [comment]
The maxmind geoip db uses a particualr structure, it links the ip to a location object, that contains the rest of the info, to be able to re utilize.
I did not find any way in mmdbctl to perform a similar approach

**Comment by abdullahdevrel** [comment]
Thanks. Paging @max-ipinfo who might have some clue around this issue.

**Comment by max-ipinfo** [comment]
@MarianoFacundoArch could you provide a simple example?

We would need
- an input CSV
- the `mmdbctl` you ran 
- what you'd expect as a result, versus what you are getting

Thanks!

**Comment by MarianoFacundoArch** [comment]
Maxmind exports their info CSV from ip to location with this csv structure:
network,geoname_id,registered_country_geoname_id,represented_country_geoname_id,is_anonymous_proxy,is_satellite_provider,postal_code,latitude,longitude,accuracy_radius,is_anycast


So, basically, they link a geoname_id.
Then, they have another csv that converts the geoname_id to the data structure:

geoname_id,locale_code,continent_code,continent_name,country_iso_code,country_name,subdivision_1_iso_code,subdivision_1_name,subdivision_2_iso_code,subdivision_2_name,city_name,metro_code,time_zone,is_in_european_union


Their mmdbs highly reuse the data instead of re inserting everything for each ip block if the structure is similar to the other one.
Am I being clear enough?

**Comment by max-ipinfo** [comment]
> Their mmdbs highly reuse the data instead of re inserting everything for each ip block if the structure is similar to the other one. Am I being clear enough?

@MarianoFacundoArch sorry, I am still struggling to understand how that has to do with `mmdbctl`.

What exact `mmdbctl` command do you run? On what files? What is the output you are getting versus what you are expecting?

**Comment by MarianoFacundoArch** [comment]
Hi Max,
My question is whether mmdbctl supports actually importing two csvs, where one contains data by referencing through an ID, and then that data is taken from a separate CSV, allowing for reutilizing entire blocks of data that might be repeated in several ip blocks.
This would greatly reduce the mmdb size

**Comment by max-ipinfo** [comment]
> My question is whether mmdbctl supports actually importing two csvs, where one contains data by referencing through an ID, and then that data is taken from a separate CSV, allowing for reutilizing entire blocks of data that might be repeated in several ip blocks.

Thank you for explaining further; that's much clearer now!

Unfortunately, we have no immediate plans for `mmdbctl` to support automatically denormalizing data like that. You should be able do this with Maxmind's library (https://github.com/maxmind/mmdbwriter) by manually building your MMDB.
