### ISSUE TITLE
Compatibility with maxmind datasets

### ISSUE THREAD

**Issue by ingria** [ipinfo/mmdbctl#8]
For some reason mmdctl doesn't work with maxmind's geoip and [geolite](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data) datasets: all requests for any ip return `err: couldn't get data for x.x.x.x`.

```
mmdbctl read -f json-pretty 8.8.8.8 ./GeoLite2-Country.mmdb 
err: couldn't get data for 8.8.8.8

mmdbctl read -f json-pretty 1.1.1.0/31 ./GeoIP2-Country.mmdb
err: couldn't get data for 1.1.1.0
err: couldn't get data for 1.1.1.1
```

ipinfo dataset works fine:
```
mmdbctl read -f json-pretty 8.8.8.8 ./Ipinfo-Country.mmdb 
{
  "continent": "NA",
  "continent_name": "North America",
  "country": "US",
  "country_name": "United States"
}
```

Metadata:
```
mmdbctl metadata ./GeoIP2-Country.mmdb 
- Binary Format 2.0
- Database Type GeoIP2-Country
- IP Version    6
- Record Size   24
- Node Count    1201540
- Description   
    en GeoIP2 Country database
- Languages     de, en, es, fr, ja, pt-BR, ru, zh-CN
- Build Epoch   1647287311
```

Is it possible to make them work together?

**Comment by rm-Umar** [comment]
Thank you @ingria for reporting. Will look into it soon!

**Comment by UmanShahzad** [comment]
This is likely because of https://github.com/ipinfo/mmdbctl/issues/2 - the geolite2/geoip2 datasets have nested structures which we don't yet support properly.

**Comment by ingria** [comment]
It would be nice to be able to use ipinfo mmdbs as drop-in replacement for maxmind datasets. The problem is that the most existing services only supports the “nested” structure.

e.g. https://nginx.org/en/docs/http/ngx_http_geoip_module.html

**Comment by UmanShahzad** [comment]
We're going to implement this very soon, within a week or two. No worries!

**Comment by UmanShahzad** [comment]
This is fixed - can anyone here who was looking for this use case check and provide feedback?

**Comment by ingria** [comment]
I can confirm that maxmind dbs are now readable 👍

Is it possible to _write_ mmdb with mmdbctl using nested structure?

**Comment by UmanShahzad** [comment]
@ingria Yes, if you have a JSON file with nested structures, it'll be written as a natively nested structure in the MMDB file too.

Lemme know if you face any issues, happy to debug.

**Comment by ingria** [comment]
Understood, thanks!

**Comment by 5721309** [comment]
Sorry if I'm missing something obvious. I try to import from .json (with nested structures) to .mmdb. It gives me such errors: 
```txt
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 1 [running]:
github.com/ipinfo/mmdbctl/lib.CmdImport({0x0, {0x7ffdcd4baed2, 0x14}, {0x7ffdcd4baeed, 0x1c}, 0x0, 0x0, 0x0, {0x0, 0x0, ...}, ...}, ...)
        /Users/ipinfo/Work/ipinfo_public/mmdbctl_master/lib/cmd_import.go:376 +0x1a85
main.cmdImport()
        /Users/ipinfo/Work/ipinfo_public/mmdbctl_master/cmd_import.go:150 +0xfd
main.main()
        /Users/ipinfo/Work/ipinfo_public/mmdbctl_master/main.go:36 +0xaf
```

Unfortunately, i don't know Go language and cannot understand this issue. Can anyone explain what I do wrong? JSON that I use looks like this:
```json
[
  {
    "range": "10.0.1.0/24",
    "continent": {
      "geoname_id": 6255000
    },
    "country": {
      "geoname_id": 2017000
    },
    "subdivisions": [
      {
        "geoname_id": 536000
      }
    ],
    "city": {
      "geoname_id": 498000
    },
    "location": {
      "latitude": 63,
      "longitude": 28,
      "accuracy_radius": 5
    }
  },
  {
    "range": "10.0.3.0/25",
    "continent": {
      "geoname_id": 6255000
    },
    "country": {
      "geoname_id": 2017000
    },
    "subdivisions": [
      {
        "geoname_id": 1488000
      }
    ],
    "city": {
      "geoname_id": 1488000
    },
    "location": {
      "latitude": 45,
      "longitude": 55,
      "accuracy_radius": 1
    }
  },
  {
    "range": "10.0.3.128/25",
    "continent": {
      "geoname_id": 6255000
    },
    "country": {
      "geoname_id": 2017000
    },
    "subdivisions": [
      {
        "geoname_id": 1488000
      }
    ],
    "city": {
      "geoname_id": 1488000
    },
    "location": {
      "latitude": 52,
      "longitude": 62,
      "accuracy_radius": 1
    }
  }
]
```
And import cmd is the following:
```sh
mmdbctl import --in to-import-geoip.json --out imported-from-json-geoip.mmdb
```

**Comment by joaoaxerb** [comment]
Hello @5721309 

I have the same issue. Have you been able to figure this out?

Looks like mmdbctl does not read arrays. How can we list multiple IP ranges in the json to convert into .mmdb file using mmdbctl import?
